### ISSUE TITLE
docs: use `eslint-doc-generator`

### ISSUE THREAD

**Issue by MichaelDeBoey** [eslint-community/eslint-plugin-mysticatea#42]
@bmish created this awesome library that brings a unified way of rule docs
https://github.com/bmish/eslint-doc-generator

**Comment by bmish** [comment]
It looks like [eslint-doc-generator](https://github.com/bmish/eslint-doc-generator) doesn't support this plugin yet because it has a lot of foreign rules (imported from another ESLint plugin and re-exported). I filed an issue to track this scenario:

* https://github.com/bmish/eslint-doc-generator/issues/257
